### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - XXX"

### ISSUE THREAD

**Issue by Golumpa** [mewin/WGFlyFlag#1]
For some reason with the very latest Spigot, WorldGuard WGCustomFlags and WGFlyFlag from the dev repositories i am getting this error. I have seen a few others also getting this error with the same setup as me.

```
[16:19:46 WARN]: Exception in thread "Craft Scheduler Thread - 160"
[16:19:46 WARN]: org.apache.commons.lang.UnhandledException: Plugin WGFlyFlag v0.2 generated an exception while executing task 9178
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
        at com.mewin.wgFlyFlag.RegionListener.updateFlyFlag(RegionListener.java:73)
        at com.mewin.wgFlyFlag.RegionListener.onUpdate(RegionListener.java:47)
        at com.mewin.wgFlyFlag.WGFlyFlagPlugin$1.run(WGFlyFlagPlugin.java:82)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by mewin** [comment]
Which version of WorldGuard are you using? The dev versions are only compatible with WG 6.

**Comment by Golumpa** [comment]
I am currently using WorldGuard 6.0.0-SNAPSHOT.1483

With the latest builds on the ci build server

**Comment by Golumpa** [comment]
Any updates on this?

**Comment by Golumpa** [comment]
No?

**Comment by xtechgamer735** [comment]
Try the latest version of the plugin thats updated for 1.8/WorldGuard6
